# -*- mode: snippet -*-
# name: Gemfile
# key: Gemfile
# group: Gemfile
# --
source 'https://rubygems.org'

group :development do
  gem 'byebug', '~> 10.0', '>= 10.0.2'
  gem 'flay', '~> 2.12'
  gem 'flog', '~> 4.6', '>= 4.6.2'
  gem 'guard', '~> 2.14', '>= 2.14.2'
  gem 'guard-bundler', '~> 2.1'
  gem 'guard-minitest', '~> 2.4', '>= 2.4.6'
  gem 'guard-reek', '~> 1.2'
  gem 'guard-rubocop', '~> 1.3'
  gem 'guard-shell', '~> 0.7.1'
  gem 'rake', '~> 12.3', '>= 12.3.1'
  gem 'reek', '~> 5.0', '>= 5.0.2'
  gem 'rubocop', '~> 0.58.2'
end

group :test do
  gem 'minitest', '~> 5.11', '>= 5.11.3'
end
